#!/bin/bash
set -e

if [[ -d "./maps/tiles" ]]
then
    rm -rf ./maps/tiles
fi
mkdir ./maps/tiles

cp ./maps/metadata.json ./maps/tiles/metadata.json
aws s3 sync ./maps/tiles s3://vfr-green-artifacts-245819277863/maps/world-vfr
