#!/bin/bash
set -e

tsc --build --clean
tsc --build
npm run generate_terminal
cd data
jq --sort-keys . terminal_metadata.json > metadata2.json
mv metadata2.json terminal_metadata.json
cd ..
tsc --build --clean
