service: adds-data-collection
provider:
  name: aws
  runtime: nodejs12.x

functions:
  collect:
    handler: src/index.handler
    events:
      - http: GET handler

package:
  exclude:
    - src/*.ts
    - package.json
    - package-lock.json
    - README.md
    - tsconfig.json
    - compile
    - deploy