#!/bin/bash
set -e
read -p "Do you want to deploy? (y/n) " yn
case $yn in
	[Yy]* ) echo "Deploying...";;
	[Nn]* ) exit;;
	* ) exit;;
esac

npm run generate
rm -rf dist/maps
rm -rf dist/metar
aws s3 sync ./dist s3://blueskycharts.com
