#!/bin/bash
set -e
read -p "Do you want to deploy? (y/n) " yn
case $yn in
	[Yy]* ) echo "Deploying...";;
	[Nn]* ) exit;;
	* ) exit;;
esac

bundle exec jekyll build
aws s3 sync ./_site s3://blueskycharts.com --size-only
